vim.api.nvim_create_user_command('BufOnly', function()
  pcall(vim.api.nvim_command, "exec '%bd|e#|bd#'")
end, {})

vim.api.nvim_create_user_command('Q', function()
  pcall(vim.api.nvim_command, 'q')
end, {})
vim.api.nvim_create_user_command('Qa', function()
  pcall(vim.api.nvim_command, 'qa')
end, {})
